# Generated by Django 6.0.6 on 2026-06-26 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('collected', 'Sample Collected'), ('transferred', 'Transferred'), ('received', 'Received at Lab'), ('stored', 'Stored'), ('retrieved', 'Retrieved from Storage'), ('analysed', 'Sent for Analysis'), ('disposed', 'Disposed')], max_length=20)),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('condition', models.CharField(blank=True, choices=[('intact', 'Intact'), ('damaged', 'Damaged'), ('compromised', 'Compromised')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfers_received', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_records', to='lims.sample')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfers_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chain_of_custody',
                'ordering': ['sample', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QCSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_id', models.CharField(max_length=50, unique=True)),
                ('qc_type', models.CharField(choices=[('blank', 'Blank'), ('control', 'Control'), ('spike', 'Spike'), ('duplicate', 'Duplicate'), ('reference', 'Reference Material'), ('calibrator', 'Calibrator')], max_length=20)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('tolerance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_samples_run', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_samples', to='lims.test')),
                ('worksheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_samples', to='lims.worksheet')),
            ],
            options={
                'db_table': 'qc_samples',
                'ordering': ['-created_at'],
            },
        ),
    ]
