# Generated by Django 6.0.6 on 2026-06-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_add_qcsample_chainofcustody'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chainofcustody',
            table='chain_of_custody_events',
        ),
    ]
