# Generated by Django 6.0.6 on 2026-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_add_record_locking'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='senaite_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_synced_from_senaite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='senaite_ar_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='senaite_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
