# Generated by Django 6.0.6 on 2026-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_senaite_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletype',
            name='prefix',
            field=models.CharField(max_length=10),
        ),
    ]
