# Generated by Django 6.0.6 on 2026-07-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_sampletype_prefix_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='collector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('acceptable', 'Acceptable'), ('compromised', 'Compromised'), ('not_acceptable', 'Not Acceptable')], max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='hold_for_qa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='sample',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('tubes', 'Tubes'), ('vials', 'Vials'), ('bags', 'Bags'), ('slides', 'Slides')], max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='receipt_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='sampling_deviation',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('temperature_excursion', 'Temperature Excursion'), ('delayed_transport', 'Delayed Transport'), ('haemolysis', 'Haemolysis')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='sample',
            name='seal_condition',
            field=models.CharField(blank=True, choices=[('intact', 'Intact'), ('broken', 'Broken'), ('missing', 'Missing')], max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='seal_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='storage_requirement',
            field=models.CharField(blank=True, choices=[('2_8c', '2–8 °C (Refrigerated)'), ('minus_20c', '-20 °C (Frozen)'), ('minus_80c', '-80 °C (Ultra-frozen)'), ('room_temp', 'Room Temperature')], max_length=20),
        ),
    ]
