# Generated by Django 6.0.6 on 2026-07-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_add_receipt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletype',
            name='senaite_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='senaite_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
