# Generated by Django 6.0.6 on 2026-07-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_add_senaite_uid_to_test_sampletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='analysis_specification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='batch_sub_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='cc_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='cc_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='client_order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='client_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='client_sample_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='composite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='container_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='environmental_conditions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='internal_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='preservation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_point',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
