# Generated by Django 6.0.6 on 2026-07-08 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_unique_client_id'),
        ('lims', '0009_new_sample_fields_test_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['sample'], name='ar_sample_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['status'], name='ar_status_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['status'], name='result_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status'], name='sample_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['client'], name='sample_client_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['created_at'], name='sample_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status', 'client'], name='sample_status_client_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetassignment',
            index=models.Index(fields=['worksheet'], name='wa_worksheet_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetassignment',
            index=models.Index(fields=['analysis_request'], name='wa_ar_idx'),
        ),
    ]
