# Generated by Django 6.0.6 on 2026-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_add_sample_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='preferred_storage_label_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sample',
            name='preferred_storage_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
