# Generated by Django 6.0.6 on 2026-07-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_preferred_storage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sample_type_uid', models.CharField(blank=True, max_length=100)),
                ('sample_type_name', models.CharField(blank=True, max_length=200)),
                ('analysis_services', models.JSONField(blank=True, default=list)),
                ('container', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sample_templates',
                'ordering': ['name'],
            },
        ),
    ]
