# Generated by Django 6.0.6 on 2026-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_add_sample_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('analysis_services', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analysis_profiles',
                'ordering': ['name'],
            },
        ),
    ]
