# Generated by Django 6.0.6 on 2026-07-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_qcsample_is_reviewed_qcsample_review_notes_and_more'),
        ('lims', '0014_add_analysis_profile'),
    ]

    operations = [
    ]
