# Generated by Django 6.0.6 on 2026-07-11 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_merge_20260710_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-80), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='specification',
            name='max_operator',
            field=models.CharField(choices=[('>=', 'Greater than or equal (>=)'), ('>', 'Greater than (>)'), ('<=', 'Less than or equal (<=)'), ('<', 'Less than (<)')], default='<=', max_length=5),
        ),
        migrations.AlterField(
            model_name='specification',
            name='min_operator',
            field=models.CharField(choices=[('>=', 'Greater than or equal (>=)'), ('>', 'Greater than (>)'), ('<=', 'Less than or equal (<=)'), ('<', 'Less than (<)')], default='>=', max_length=5),
        ),
    ]
