# Generated by Django 6.0.6 on 2026-07-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_add_processing_status'),
        ('lims', '0016_alter_chainofcustody_temperature_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheets', to='instruments.instrument'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheets', to='lims.method'),
        ),
        migrations.AddField(
            model_name='worksheetassignment',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_assignments', to='instruments.instrument'),
        ),
        migrations.AddField(
            model_name='worksheetassignment',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_assignments', to='lims.method'),
        ),
    ]
