# Generated by Django 6.0.6 on 2026-07-14 07:30

from django.db import migrations, models


def backfill_partitions(apps, schema_editor):
    """Fold the old flat container + analysis_services fields into a single
    partition row so existing templates keep working under the new schema."""
    SampleTemplate = apps.get_model('lims', 'SampleTemplate')
    for tpl in SampleTemplate.objects.all():
        services = tpl.analysis_services or []
        container = tpl.container or ''
        if not services and not container:
            continue
        tpl.partitions = [{
            'part_id': 'part-1',
            'container_uid': '',
            'container_name': container,
            'preservation_uid': '',
            'preservation_name': '',
            'sample_type_uid': '',
            'sample_type_name': '',
            'services': [
                {'uid': s.get('uid', ''), 'title': s.get('title', ''), 'hidden': False}
                for s in services
            ],
        }]
        tpl.save(update_fields=['partitions'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0017_add_worksheet_instrument_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletemplate',
            name='auto_partition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='composite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='partitions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='sample_point_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='sample_point_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sampletemplate',
            name='sampling_required',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_partitions, noop_reverse),
        migrations.RemoveField(
            model_name='sampletemplate',
            name='analysis_services',
        ),
        migrations.RemoveField(
            model_name='sampletemplate',
            name='container',
        ),
    ]
