# Generated by Django 6.0.6 on 2026-07-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0017_sample_senaite_sync_status"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="method",
                    name="accredited",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="method",
                    name="instructions",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AlterField(
                    model_name="sample",
                    name="analysis_specification",
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE methods "
                        "ADD COLUMN IF NOT EXISTS accredited boolean DEFAULT false NOT NULL;"
                        "ALTER TABLE methods "
                        "ADD COLUMN IF NOT EXISTS instructions text DEFAULT '' NOT NULL;"
                        "ALTER TABLE samples "
                        "ALTER COLUMN analysis_specification DROP NOT NULL;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
