# Generated by Django 6.0.6 on 2026-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0018_add_sample_template_partitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('formula', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calculations',
            },
        ),
        migrations.AddField(
            model_name='method',
            name='accredited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='method',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='method_documents/'),
        ),
        migrations.AddField(
            model_name='method',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='method',
            name='calculations',
            field=models.ManyToManyField(blank=True, related_name='methods', to='lims.calculation'),
        ),
    ]
