# Generated by Django 6.0.6 on 2026-07-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0019_add_method_fields_and_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAnalysisSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='dynamic_analysis_specs/')),
                ('senaite_uid', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dynamic_analysis_specifications',
            },
        ),
        migrations.AddField(
            model_name='specification',
            name='dynamic_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='lims.dynamicanalysisspecification'),
        ),
    ]
