# Generated by Django 6.0.6 on 2026-07-14 15:24, hand-edited to insert a data
# migration step before sample_type/dynamic_spec are dropped from Specification
# (see AnalysisSpecification/Specification docstrings in models.py — this
# reworks "one row per test+sample_type" into "one header (title+sample_type)
# containing a grid of per-test rows", matching SENAITE's own structure).

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_rows_to_headers(apps, schema_editor):
    """Group existing Specification rows by sample_type into a synthetic
    AnalysisSpecification header per sample_type, then point each row at its
    new header. Runs before sample_type/dynamic_spec are dropped from
    Specification, so both are still readable here."""
    Specification = apps.get_model('lims', 'Specification')
    AnalysisSpecification = apps.get_model('lims', 'AnalysisSpecification')

    header_by_sample_type = {}
    for row in Specification.objects.all():
        sample_type_id = row.sample_type_id
        if sample_type_id not in header_by_sample_type:
            sample_type = row.sample_type
            header = AnalysisSpecification.objects.create(
                title=f"{sample_type.name} Specification",
                sample_type_id=sample_type_id,
                dynamic_spec_id=row.dynamic_spec_id,
                is_active=True,
            )
            header_by_sample_type[sample_type_id] = header.id
        row.specification_id = header_by_sample_type[sample_type_id]
        row.save(update_fields=['specification'])


def reverse_noop(apps, schema_editor):
    # Not meaningfully reversible (would need to flatten headers back down,
    # discarding min_warn/max_warn/out_of_range_* with no equivalent on the
    # old shape) — reversing this migration is not supported.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0020_add_dynamic_analysis_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_specifications', to='lims.dynamicanalysisspecification')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_specifications', to='lims.sampletype')),
            ],
            options={
                'db_table': 'analysis_specifications',
            },
        ),
        migrations.AddField(
            model_name='specification',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='lims.analysisspecification'),
        ),
        migrations.RunPython(migrate_existing_rows_to_headers, reverse_noop),
        migrations.RemoveField(
            model_name='specification',
            name='dynamic_spec',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='sample_type',
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='lims.analysisspecification'),
        ),
        migrations.AddField(
            model_name='specification',
            name='max_warn',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='min_warn',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='out_of_range_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='specification',
            name='out_of_range_high',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='out_of_range_low',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
