# Generated by Django 6.0.6 on 2026-07-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0021_specification_header_rework'),
    ]

    operations = [
        # Hand-written as raw SQL (not a plain AlterField) because the column has
        # to become nullable BEFORE the blank/non-numeric string values can be
        # nulled out, and only THEN can the type change to integer — doing it in
        # Django's default AlterField order tries to null out rows while the
        # column is still NOT NULL and fails. state_operations keeps the ORM's
        # model state in sync without letting Django generate its own conflicting
        # SQL for this field.
        migrations.RunSQL(
            sql="""
                ALTER TABLE samples ALTER COLUMN analysis_specification DROP NOT NULL;
                UPDATE samples SET analysis_specification = NULL
                    WHERE analysis_specification !~ '^[0-9]+$'
                       OR analysis_specification::integer NOT IN (SELECT id FROM analysis_specifications);
                ALTER TABLE samples ALTER COLUMN analysis_specification
                    TYPE integer USING NULLIF(analysis_specification, '')::integer;
                ALTER TABLE samples ALTER COLUMN analysis_specification DROP DEFAULT;
                ALTER TABLE samples ADD CONSTRAINT samples_analysis_specification_fk
                    FOREIGN KEY (analysis_specification) REFERENCES analysis_specifications(id)
                    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='sample',
                    name='analysis_specification',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='samples', to='lims.analysisspecification',
                        db_column='analysis_specification',
                    ),
                ),
            ],
        ),
    ]
