# Generated by Django 6.0.6 on 2026-07-15 06:47, then hand-edited to preserve
# existing data: the AddField/CreateModel steps run BEFORE the old test
# FK/M2M fields are dropped, with a RunPython step in between that copies
# each row's Test name across (Test.senaite_uid was never populated in this
# codebase's existing data, so only the name carries over — acceptable, since
# these rows predate any real SENAITE-service linkage anyway).
import django.db.models.deletion
from django.db import migrations, models


def copy_test_data_to_senaite_fields(apps, schema_editor):
    Specification = apps.get_model('lims', 'Specification')
    WorksheetAssignment = apps.get_model('lims', 'WorksheetAssignment')
    QCSample = apps.get_model('lims', 'QCSample')
    AnalysisRequest = apps.get_model('lims', 'AnalysisRequest')
    AnalysisRequestAnalysis = apps.get_model('lims', 'AnalysisRequestAnalysis')

    for spec in Specification.objects.select_related('test').all():
        if spec.test_id:
            spec.senaite_service_uid = spec.test.senaite_uid or ''
            spec.senaite_service_name = spec.test.name
            spec.save(update_fields=['senaite_service_uid', 'senaite_service_name'])

    for wa in WorksheetAssignment.objects.select_related('test').all():
        if wa.test_id:
            wa.senaite_service_uid = wa.test.senaite_uid or ''
            wa.senaite_service_name = wa.test.name
            wa.save(update_fields=['senaite_service_uid', 'senaite_service_name'])

    for qc in QCSample.objects.select_related('test').all():
        if qc.test_id:
            qc.senaite_service_uid = qc.test.senaite_uid or ''
            qc.senaite_service_name = qc.test.name
            qc.save(update_fields=['senaite_service_uid', 'senaite_service_name'])

    for ar in AnalysisRequest.objects.prefetch_related('tests').all():
        for test in ar.tests.all():
            AnalysisRequestAnalysis.objects.create(
                analysis_request=ar,
                senaite_service_uid=test.senaite_uid or '',
                senaite_service_name=test.name,
            )


def noop_reverse(apps, schema_editor):
    """Data loss on reverse is unavoidable — the old test FK/M2M columns
    won't exist to restore into. Nothing to do here."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0022_sample_analysis_specification_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcsample',
            name='senaite_service_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='qcsample',
            name='senaite_service_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='senaite_service_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='specification',
            name='senaite_service_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worksheetassignment',
            name='senaite_service_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='worksheetassignment',
            name='senaite_service_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='AnalysisRequestAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senaite_service_uid', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('senaite_service_name', models.CharField(blank=True, max_length=200)),
                ('analysis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='lims.analysisrequest')),
            ],
            options={
                'db_table': 'analysis_request_analyses',
            },
        ),
        migrations.AddIndex(
            model_name='analysisrequestanalysis',
            index=models.Index(fields=['analysis_request'], name='ara_ar_idx'),
        ),
        migrations.RunPython(copy_test_data_to_senaite_fields, noop_reverse),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='worksheetassignment',
            name='test',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='test',
        ),
        migrations.RemoveField(
            model_name='qcsample',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
