# Generated by Django 6.0.6 on 2026-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_add_processing_status'),
        ('lims', '0023_remove_test_model_use_senaite_services'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worksheetassignment',
            constraint=models.UniqueConstraint(fields=('analysis_request', 'senaite_service_uid'), name='uniq_ar_service_assignment'),
        ),
    ]
