# Generated by Django 6.0.6 on 2026-07-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0024_worksheet_assignment_unique_ar_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sampling_deviation',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
