# Generated by Django 6.0.6 on 2026-07-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0026_merge_vinod_staging_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='analysis_specification',
            field=models.ForeignKey(blank=True, db_column='analysis_specification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='lims.analysisspecification'),
        ),
    ]
