# Generated by Django 6.0.6 on 2026-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0027_alter_method_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='senaite_attachment_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
