# Generated by Django 6.0.6 on 2026-07-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0028_add_sample_senaite_attachment_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisProfile',
        ),
    ]
