# Generated by Django 6.0.6 on 2026-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0029_remove_analysis_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='calculations',
        ),
        migrations.AddField(
            model_name='method',
            name='senaite_calculation_uids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
