# Generated by Django 6.0.6 on 2026-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0030_remove_local_calculation_use_senaite_uids'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='purpose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='seal_status',
            field=models.CharField(blank=True, choices=[('intact', 'Seal Intact'), ('broken', 'Seal Broken'), ('not_sealed', 'Not Sealed')], max_length=20),
        ),
    ]
