# Generated by Django 6.0.6 on 2026-07-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0032_add_custody_completed_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='action',
            field=models.CharField(choices=[('collected', 'Sample Collected'), ('transferred', 'Transferred'), ('received', 'Received at Lab'), ('batched', 'Added to Batch'), ('stored', 'Stored'), ('retrieved', 'Retrieved from Storage'), ('analysed', 'Sent for Analysis'), ('completed', 'Sample Completed'), ('disposed', 'Disposed')], max_length=20),
        ),
    ]
