# Generated by Django 6.0.6 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_approval_senaite_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='priority',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
