version: '3.8'

services:
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8089:8088"
    volumes:
      - ./superset_config.py:/app/superset_home/superset_config.py
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY:-YOUR_SUPERSET_SECRET_KEY}
      - SUPERSET_CORS_ORIGINS=${SUPERSET_CORS_ORIGINS:-http://localhost:3000}
      - SUPERSET_CONFIG_PATH=/app/superset_home/superset_config.py
