# Generated by Django 6.0.6 on 2026-06-30 09:24

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_senaite_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='salutation',
            field=models.CharField(blank=True, choices=[('', '—'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
