# Generated by Django 6.0.6 on 2026-06-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_field_updates'),
        ('core', '0005_pending_model_changes'),
    ]

    operations = [
    ]
