# Generated by Django 6.0.6 on 2026-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0005_field_updates_0005_pending_model_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
