# Generated by Django 6.0.6 on 2026-07-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_unique_client_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="client",
                    name="cc_emails",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="client",
                    name="organization_type",
                    field=models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE clients "
                        "ADD COLUMN IF NOT EXISTS cc_emails text DEFAULT '' NOT NULL;"
                        "ALTER TABLE clients "
                        "ADD COLUMN IF NOT EXISTS organization_type varchar(100) DEFAULT '' NOT NULL;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE clients DROP COLUMN IF EXISTS cc_emails;"
                        "ALTER TABLE clients DROP COLUMN IF EXISTS organization_type;"
                    ),
                ),
            ],
        ),
    ]
