# Generated by Django 6.0.6 on 2026-07-10 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_unique_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cc_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bulk_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\s\\-\\+\\(\\)]*$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\s\\-\\+\\(\\)]*$', 'Enter a valid fax number.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='member_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\s\\-\\+\\(\\)]*$', 'Enter a valid mobile number.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[\\d\\s\\-\\+\\(\\)]*$', 'Enter a valid phone number.')]),
        ),
    ]
