# Generated by Django 6.0.6 on 2026-07-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_client_cc_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('Pharmaceutical', 'Pharmaceutical'), ('Biotechnology', 'Biotechnology'), ('Environmental', 'Environmental'), ('Healthcare', 'Healthcare'), ('Food & Beverage', 'Food & Beverage'), ('Academic', 'Academic'), ('Government', 'Government'), ('Other', 'Other')], max_length=50),
        ),
    ]
