# Generated by Django 6.0.6 on 2026-07-23 08:54

from django.db import migrations, models


def remap_roles(apps, schema_editor):
    """Old roles that don't carry over 1:1 into the new matrix set:
    reviewer → verifier, receptionist → lab_clerk. Runs per-schema under
    migrate_schemas, so it remaps users in every tenant it's applied to."""
    User = apps.get_model('core', 'User')
    User.objects.filter(role='reviewer').update(role='verifier')
    User.objects.filter(role='receptionist').update(role='lab_clerk')


def reverse_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(role='verifier').update(role='reviewer')
    User.objects.filter(role='lab_clerk').update(role='receptionist')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_core_client_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('lab_clerk', 'Lab Clerk'), ('sampler', 'Sampler'), ('analyst', 'Analyst'), ('verifier', 'Verifier'), ('lab_manager', 'Lab Manager'), ('publisher', 'Publisher'), ('manager', 'Manager'), ('admin', 'Administrator')], default='analyst', max_length=20),
        ),
        migrations.RunPython(remap_roles, reverse_roles),
    ]
