# Generated by Django 6.0.6 on 2026-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_inventory_split_item_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='columns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='senaite_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='slot_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='location_type',
            field=models.CharField(choices=[('room', 'Room'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('box', 'Box'), ('box_location', 'Box Location')], default='room', max_length=50),
        ),
    ]
