# Generated by Django 6.0.6 on 2026-07-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_storagelocation_box_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='location_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='location_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='location_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='senaite_location_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='shelf_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='shelf_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='shelf_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='site_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='site_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='site_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
