# Generated by Django 6.0.6 on 2026-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_storagelocation_senaite_metadata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='storage_location_no_self_parent'),
        ),
    ]
