# Generated by Django 6.0.6 on 2026-07-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_no_self_parent_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='assigned_sample_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
