# Generated by Django 6.0.6 on 2026-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_assigned_sample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='label_code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
