# Generated by Django 6.0.6 on 2026-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_backfill_label_codes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['parent'], name='storage_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['location_type'], name='storage_type_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['is_occupied'], name='storage_occupied_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['assigned_sample_id'], name='storage_sample_id_idx'),
        ),
    ]
