# Generated by Django 6.0.6 on 2026-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorytransaction_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='senaite_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
