# Generated by Django 6.0.6 on 2026-07-14 07:19

from django.db import migrations, models


def rename_room_to_building(apps, schema_editor):
    """Before this migration, 'room' was the only top-level type (what senaite_
    service.py maps to StorageFacility). This migration introduces a genuinely
    new 'room' type (StoragePosition, must sit under a building) — every
    existing 'room' row predates that distinction and meant the old top-level
    type, so it becomes 'building' here."""
    StorageLocation = apps.get_model('inventory', 'StorageLocation')
    StorageLocation.objects.filter(location_type='room').update(location_type='building')


def rename_building_to_room(apps, schema_editor):
    StorageLocation = apps.get_model('inventory', 'StorageLocation')
    StorageLocation.objects.filter(location_type='building').update(location_type='room')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_storage_location_senaite_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagelocation',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='location_title',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='senaite_location_type',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='shelf_code',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='shelf_description',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='shelf_title',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='site_code',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='site_title',
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='location_type',
            field=models.CharField(choices=[('building', 'Building'), ('room', 'Room'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('box', 'Box'), ('box_location', 'Box Location')], default='building', max_length=50),
        ),
        migrations.RunPython(rename_room_to_building, rename_building_to_room),
    ]
