# Generated by Django 6.0.6 on 2026-07-08 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('coa', 'Certificate of Analysis'), ('worksheet', 'Worksheet Report'), ('qc', 'QC Report'), ('inventory', 'Inventory Report'), ('instrument', 'Instrument Report'), ('custom', 'Custom Report')], default='coa', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
