# Generated by Django 6.0.6 on 2026-07-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_unique_client_id'),
        ('reporting', '0003_add_failed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='client',
            field=models.ForeignKey(blank=True, help_text='If set, used only when generating for this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='core.client'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='header_color',
            field=models.CharField(default='#003366', max_length=7),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='report_logos/'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
