from django.db import models
from django.conf import settings


DEFAULT_COA_FIELDS = [
    # --- Header ---
    {"key": "lab_name",           "label": "Laboratory Name",        "value": "XelLabs",                                 "visible": True,  "section": "header",    "editable_value": True},
    {"key": "lab_subtitle",       "label": "Laboratory Subtitle",    "value": "Laboratory Information Management System", "visible": True,  "section": "header",    "editable_value": True},
    {"key": "doc_title",          "label": "Document Title",         "value": "CERTIFICATE OF ANALYSIS",                 "visible": True,  "section": "header",    "editable_value": True},
    {"key": "accreditation",      "label": "Accreditation Number",   "value": "",                                        "visible": False, "section": "header",    "editable_value": True},
    # --- Report Info ---
    {"key": "section_report",     "label": "Report Info Section Header", "value": "Report Information",                  "visible": True,  "section": "report_info", "editable_value": True},
    {"key": "field_report_id",    "label": "Report ID Label",        "value": "Report ID",                               "visible": True,  "section": "report_info", "editable_value": True},
    {"key": "field_report_title", "label": "Report Title Label",     "value": "Report Title",                            "visible": True,  "section": "report_info", "editable_value": True},
    {"key": "field_generated_by", "label": "Generated By Label",     "value": "Generated By",                            "visible": True,  "section": "report_info", "editable_value": True},
    {"key": "field_generated_at", "label": "Generated At Label",     "value": "Generated At",                            "visible": True,  "section": "report_info", "editable_value": True},
    {"key": "field_published_at", "label": "Published At Label",     "value": "Published At",                            "visible": True,  "section": "report_info", "editable_value": True},
    # --- Client Info ---
    {"key": "section_client",     "label": "Client Section Header",  "value": "Client Information",                      "visible": True,  "section": "client",    "editable_value": True},
    {"key": "field_client_name",  "label": "Client Name Label",      "value": "Client Name",                             "visible": True,  "section": "client",    "editable_value": True},
    {"key": "field_client_code",  "label": "Client Code Label",      "value": "Client Code",                             "visible": True,  "section": "client",    "editable_value": True},
    {"key": "field_client_email", "label": "Contact Email Label",    "value": "Contact Email",                           "visible": True,  "section": "client",    "editable_value": True},
    {"key": "field_client_phone", "label": "Contact Phone Label",    "value": "Contact Phone",                           "visible": True,  "section": "client",    "editable_value": True},
    # --- Sample Info ---
    {"key": "section_sample",     "label": "Sample Section Header",  "value": "Sample Information",                      "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_sample_id",    "label": "Sample ID Label",        "value": "Sample ID",                               "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_sample_type",  "label": "Sample Type Label",      "value": "Sample Type",                             "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_barcode",      "label": "Barcode Label",          "value": "Barcode",                                 "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_status",       "label": "Status Label",           "value": "Status",                                  "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_collection",   "label": "Collection Date Label",  "value": "Collection Date",                         "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_received",     "label": "Received Date Label",    "value": "Received Date",                           "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_storage",      "label": "Storage Location Label", "value": "Storage Location",                        "visible": True,  "section": "sample",    "editable_value": True},
    {"key": "field_description",  "label": "Description Label",      "value": "Description",                             "visible": True,  "section": "sample",    "editable_value": True},
    # --- Results ---
    {"key": "section_results",    "label": "Results Section Header", "value": "Analysis Results",                        "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_test",           "label": "Test Column Header",     "value": "Test",                                    "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_method",         "label": "Method Column Header",   "value": "Method",                                  "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_result",         "label": "Result Value Column",    "value": "Result Value",                            "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_unit",           "label": "Unit Column Header",     "value": "Unit",                                    "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_spec",           "label": "Specification Column",   "value": "Specification",                           "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_status",         "label": "Status Column Header",   "value": "Status",                                  "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_analyst",        "label": "Analyst Column Header",  "value": "Analyst",                                 "visible": True,  "section": "results",   "editable_value": True},
    {"key": "col_verified_by",    "label": "Verified By Column",     "value": "Verified By",                             "visible": True,  "section": "results",   "editable_value": True},
    # --- QC ---
    {"key": "section_qc",         "label": "QC Section Header",      "value": "QC Summary",                              "visible": True,  "section": "qc",        "editable_value": True},
    # --- Authorisation ---
    {"key": "section_auth",       "label": "Authorisation Section Header", "value": "Authorisation",                     "visible": True,  "section": "signature", "editable_value": True},
    {"key": "sig_analyst_label",  "label": "Analyst Signature Label","value": "Reviewed By (Analyst)",                  "visible": True,  "section": "signature", "editable_value": True},
    {"key": "sig_reviewer_label", "label": "Reviewer Signature Label","value": "Approved By (Reviewer / Lab Manager)",  "visible": True,  "section": "signature", "editable_value": True},
    # --- Footer ---
    {"key": "footer_left",        "label": "Footer Left Text",       "value": "XelLabs LIMS — Confidential",            "visible": True,  "section": "footer",    "editable_value": True},
    {"key": "footer_disclaimer",  "label": "Footer Disclaimer",      "value": "",                                        "visible": False, "section": "footer",    "editable_value": True},
]


class ReportTemplate(models.Model):
    REPORT_TYPES = [
        ("coa", "Certificate of Analysis"),
        ("worksheet", "Worksheet Report"),
        ("qc", "QC Report"),
        ("inventory", "Inventory Report"),
        ("instrument", "Instrument Report"),
        ("custom", "Custom Report"),
    ]
    name         = models.CharField(max_length=200)
    report_type  = models.CharField(max_length=20, choices=REPORT_TYPES, default="coa")
    is_active    = models.BooleanField(default=False)
    fields       = models.JSONField(default=list)
    header_color = models.CharField(max_length=7, default="#003366")
    logo         = models.ImageField(upload_to="report_logos/", null=True, blank=True)
    client       = models.ForeignKey("core.Client", null=True, blank=True, on_delete=models.SET_NULL,
                                     related_name="report_templates",
                                     help_text="If set, used only when generating for this client.")
    created_by   = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="report_templates")
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "report_templates"
        ordering = ["-updated_at"]

    def __str__(self):
        return f"{self.name} ({self.report_type})"

    def get_logo_url(self) -> str:
        if self.logo:
            try:
                return self.logo.url
            except Exception:
                return ""
        return ""

    def get_field(self, key: str, fallback: str = "") -> str:
        for f in self.fields:
            if f.get("key") == key and f.get("visible", True):
                return f.get("value") or fallback
        return fallback


class Report(models.Model):
    STATUS = [("draft", "Draft"), ("final", "Final"), ("cancelled", "Cancelled"), ("failed", "Failed")]
    REPORT_TYPES = [
        ("coa", "Certificate of Analysis"),
        ("worksheet", "Worksheet Report"),
        ("qc", "QC Report"),
        ("inventory", "Inventory Report"),
        ("instrument", "Instrument Report"),
        ("custom", "Custom Report"),
    ]
    report_id = models.CharField(max_length=50, unique=True)
    report_type = models.CharField(max_length=20, choices=REPORT_TYPES)
    title = models.CharField(max_length=300)
    sample = models.ForeignKey("lims.Sample", null=True, blank=True, on_delete=models.SET_NULL,
                               related_name="reports")
    status = models.CharField(max_length=10, choices=STATUS, default="draft")
    generated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    file = models.FileField(upload_to="reports/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    published_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "reports"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.report_id} - {self.title}"
