# Generated by Django 6.0.6 on 2026-06-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0003_add_record_version'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recordversion',
            name='unique_record_version',
        ),
        migrations.RenameIndex(
            model_name='recordversion',
            new_name='record_vers_content_53e5fe_idx',
            old_name='record_ver_content_idx',
        ),
        migrations.AlterUniqueTogether(
            name='recordversion',
            unique_together={('content_type', 'object_id', 'version_number')},
        ),
    ]
