# Generated by Django 6.0.6 on 2026-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0004_detect_unmigrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('approve', 'Approved'), ('reject', 'Rejected'), ('sign', 'Signed'), ('print', 'Printed'), ('instrument_import', 'Instrument Import')], max_length=30),
        ),
    ]
