# Generated by Django 6.0.6 on 2026-07-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0005_add_extra_data_to_audit_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('approve', 'Approved'), ('reject', 'Rejected'), ('sign', 'Signed'), ('print', 'Printed'), ('instrument_import', 'Instrument Import'), ('receive', 'Received'), ('submit', 'Submitted'), ('verify', 'Verified'), ('complete', 'Completed')], max_length=30),
        ),
    ]
