# Generated by Django 6.0.6 on 2026-07-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0006_expand_auditevent_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('approve', 'Approved'), ('reject', 'Rejected'), ('sign', 'Signed'), ('print', 'Printed'), ('instrument_import', 'Instrument Import'), ('receive', 'Received'), ('submit', 'Submitted'), ('verify', 'Verified'), ('complete', 'Completed'), ('store', 'Store')], max_length=30),
        ),
    ]
