# Generated by Django 6.0.6 on 2026-07-22 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0009_auditevent_source_alter_auditevent_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField()),
                ('created_count', models.PositiveIntegerField()),
                ('skipped_count', models.PositiveIntegerField()),
                ('failed_count', models.PositiveIntegerField()),
                ('row_errors', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
