# Generated by Django 6.0.6 on 2026-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['status'], name='instrument_status_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['next_calibration'], name='instrument_next_cal_idx'),
        ),
    ]
