# Generated by Django 6.0.6 on 2026-07-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentresultimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
