# Generated by Django 6.0.6 on 2026-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_add_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='instrument',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
