# Generated by Django 6.0.6 on 2026-07-15 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_add_type_supplier_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'instrument_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'instrument_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('internal', models.BooleanField(default=False, help_text='Internal certification vs external agency')),
                ('agency', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('expiration_interval', models.PositiveIntegerField(blank=True, help_text='Days from Valid From until expiry (used if Valid To is blank)', null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='instruments.instrument')),
                ('preparator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instrument_certifications',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.instrumentlocation'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.instrumenttype'),
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('calibration', 'Calibration'), ('validation', 'Validation')], default='maintenance', max_length=50)),
                ('criteria', models.CharField(blank=True, help_text="Recurrence, e.g. 'every 30 days' or a cron-like rule", max_length=200)),
                ('considerations', models.TextField(blank=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='instruments.instrument')),
            ],
            options={
                'db_table': 'instrument_scheduled_tasks',
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('down_from', models.DateField(blank=True, help_text='Instrument out of service from', null=True)),
                ('down_to', models.DateField(blank=True, help_text='Instrument back in service on', null=True)),
                ('validator', models.CharField(blank=True, max_length=200)),
                ('work_performed', models.TextField(blank=True)),
                ('considerations', models.TextField(blank=True)),
                ('report_id', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='instruments.instrument')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instrument_validations',
                'ordering': ['-date_issued'],
            },
        ),
    ]
