# Generated by Django 6.0.6 on 2026-07-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0009_refresh_instrument_usability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='data_interface',
            field=models.CharField(blank=True, help_text='Export data interface code', max_length=200),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='dispose_until_next_calibration',
            field=models.BooleanField(default=False, help_text='Unavailable until the next valid calibration'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='import_data_interface',
            field=models.CharField(blank=True, help_text='Comma-separated import interface codes', max_length=500),
        ),
    ]
